# Generated by Django 3.2.16 on 2022-12-20 03:19

from django.db import migrations, models
import django.db.models.deletion
import recipe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/recipes/<django.db.models.fields.related.ForeignKey>/', validators=[recipe.validators.validate_file_size])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe.recipe')),
            ],
        ),
    ]
