# Generated by Django 3.2.16 on 2022-12-20 10:00

from django.db import migrations, models
import django.db.models.deletion
import recipe.models
import recipe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_recipeimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recipe.models.ingredient_image_file_path, validators=[recipe.validators.validate_file_size])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe.ingredient')),
            ],
        ),
    ]
