# Generated by Django 3.2.16 on 2022-12-20 14:02

import django.core.validators
from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_ingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=recipe.models.recipe_image_file_path, validators=[django.core.validators.MaxValueValidator(2097152)]),
        ),
    ]
