# Generated by Django 3.2.16 on 2022-12-21 15:19

from django.db import migrations, models
import recipe.models
import recipe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=recipe.models.recipe_image_file_path, validators=[recipe.validators.validate_file_size]),
        ),
    ]
